
apiVersion: v1
kind: Service
metadata:
  namespace: tekton-builds
  name: clockins-service
spec:
  selector:
    app: clockins
  ports:
    - name: http
      protocol: TCP
      port: 3004
      targetPort: 7600
      nodePort: 30004
#  externalIPs:
#    - 192.168.100.95
  type: NodePort
