apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aptos-cashoff
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.mailtrap: hello@gmail.com
spec:
  destination:
    namespace: tekton-builds ## incase of openshift change this to int
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ACE/CashOff/overlays/dev/
    repoURL: https://github.com/mfarhanSystemsltd/gitops-test.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
