apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tekton-builds
  name: clockins-deployment
  labels:
    app: clockins
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: clockins
        image: mfarhan1998/ace-test:67
